let data = [
    {
      name: "Fancy Product",
      currentPrice: "$40.00 - $80.00",
      prevPrice: "",
      buttonValue: "View Options",
      sale: false,
      star: null,
      disble: false,
    },
    {
      name: "Special Item",
      currentPrice: "$18.00",
      prevPrice: "$20.00",
      buttonValue: "Add to Cart",
      sale: true,
      star: 4,
      disble: false,
    },
    {
      name: "Sale Item",
      currentPrice: "$25.00",
      prevPrice: "$50.00",
      buttonValue: "Add to Cart",
      sale: true,
      star: null,
      disble: false,
    },
    {
      name: "Popular Item",
      currentPrice: "$40.00",
      prevPrice: "",
      buttonValue: "Add to Cart",
      sale: false,
      star: 5,
      disble: false,
    },
    {
      name: "Sale Item",
      currentPrice: "$25.00",
      prevPrice: "$50.00",
      buttonValue: "Add to Cart",
      sale: true,
      star: null,
      disble: false,
    },
    {
      name: "Fancy Product",
      currentPrice: "$120.00 - $280.00",
      prevPrice: "",
      buttonValue: "View Options",
      sale: false,
      star: null,
      disble: false,
    },
    {
      name: "Special Item",
      currentPrice: "$18.00",
      prevPrice: "$20.00",
      buttonValue: "Add to Cart",
      sale: true,
      star: 5,
      disble: false,
    },
    {
      name: "Popular Item",
      currentPrice: "$40.00",
      prevPrice: "",
      buttonValue: "Add to Cart",
      sale: false,
      star: 5,
      disble: false,
    },
  ];
  
  export default data;